// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'mirrorGame': string;
  'topBar': string;
  'tutorial': string;
  'tutorial-card': string;
}
export const cssExports: CssExports;
export default cssExports;
